### ISSUE TITLE
Madminer example is incompatible with singularity

### ISSUE THREAD

**Issue by khurtado** [scailfin/madminer-workflow#5] opened 2019-07-16 19:10 UTC
Hello, 

I'm trying to test this example in REANA + HTCondor + Singularity and noticed some failures that I just wanted to report.

1. The steps assume the starting working directory will be /home, when calling code/<script.py> ([example](https://github.com/scailfin/workflow-madminer/blob/master/example-full/steps.yml#L17)). So, each script either needs some `cd /home` at the beginning or using full paths

2. Steps that try to create directories in `/home` like [here](https://github.com/scailfin/workflow-madminer/blob/master/example-full/steps.yml#L45) won't succeed unless the container is entered as root (docker case, but not singularity) , which result in Read-only file system errors like below. It would be great if the workflow could be adapted so that the directories created were done in the relative path of the working directory in the container (so it is up to the container technology invocation to make sure that relative path has write access), like in [this example](https://github.com/reanahub/reana-demo-root6-roofit/blob/master/reana.yaml#L16)

```
Traceback (most recent call last):
  File "code/configurate.py", line 93, in <module>
    miner.save('/home/data/madminer_example.h5')
  File "/usr/local/lib/python2.7/dist-packages/madminer/core.py", line 527, in save
    create_missing_folders([os.path.dirname(filename)])
  File "/usr/local/lib/python2.7/dist-packages/madminer/utils/various.py", line 55, in create_missing_folders
    os.makedirs(folder)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '/home/data'
cp: cannot stat '/home/data/*.h5': No such file or directory
[Error] Execution failed with error code: 1
```

**Comment by lukasheinrich** [comment] 2019-07-24 16:07
hi @khurtado can you just try replacing `/home/extract` with `/tmp/extract` and see if that works?

**Comment by khurtado** [comment] 2019-07-24 16:30
@lukasheinrich: Changing `/home/extract->/tmp/extract`in the workflow steps didn't work. The problem is that the directories are not only defined in the yaml files, but are hardcoded in the python scripts that come inside the image. The steps also assume the starting directory is `/home`, so calls to relative paths there like [here](https://github.com/scailfin/workflow-madminer/blob/master/example-full/steps.yml#L17) fail. 

See some examples below:
https://github.com/scailfin/workflow-madminer/blob/master/docker/docker-madminer-physics/code/delphes.py#L82
https://github.com/scailfin/workflow-madminer/blob/master/docker/docker-madminer-physics/code/configurate.py#L93
https://github.com/scailfin/workflow-madminer/blob/master/docker/docker-madminer-physics/code/generate.py#L63-L79

**Comment by lukasheinrich** [comment] 2019-07-24 16:36
hi this will require a rebuild of the image, i'm not sure how pervasive it is but usually being able to change this using a env variable i.e. replacing with `os.environ['MADMINER_DATA']` or similar.

**Comment by khurtado** [comment] 2019-07-24 16:43
@lukasheinrich I agree using environment variables on the scripts and settings those in the workflows makes sense. Is there anybody in the NYU scailfin group maintaining this example be willing to make the changes and rebuilding image for that purpose?

**Comment by cranmer** [comment] 2019-07-24 17:29
Normally this wold be @irinaespejo, but I'm not sure if she is available right now. 
Thank you for testing and finding the issues. I'll see if I can find someone to help.
Possibly @heikomuller @alexanderheld ?

**Comment by cranmer** [comment] 2019-07-24 17:30
It's lines like this that are the problem, right?
https://github.com/scailfin/workflow-madminer/blob/master/docker/docker-madminer-ml/code/configurate_ml.py#L65

**Comment by khurtado** [comment] 2019-07-24 17:35
@cranmer Correct!

**Comment by irinaespejo** [comment] 2019-08-16 16:42
Hi @khurtado, thank you for your detailed report and apologies for the late reply, I've been away for a while. You're very right in the problem with the paths using Singularity, Lukas' suggestion is helpful and I'll go that way. I'm working on it right now so that we don't have problems like this in the future. I'll get back to you when it's done, thanks for the patience!

**Comment by khurtado** [comment] 2019-08-19 12:38
@irinaespejo Thank you!

**Comment by khurtado** [comment] 2019-08-29 17:50
@irinaespejo Awesome! Thank you, I will test this week and let you know how things go for me.

**Comment by khurtado** [comment] 2019-09-04 14:26
Hi @irinaespejo 
I tested today, but got errors due to `/madminer/data` being in read-only mode.
```
Traceback (most recent call last):
  File "/madminer/code/configurate.py", line 93, in <module>
    miner.save('/madminer/data/madminer_example.h5')
  File "/usr/local/lib/python2.7/dist-packages/madminer/core.py", line 527, in save
    create_missing_folders([os.path.dirname(filename)])
  File "/usr/local/lib/python2.7/dist-packages/madminer/utils/various.py", line 55, in create_missing_folders
    os.makedirs(folder)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '/madminer/data'
cp: cannot stat '/madminer/data/*.h5': No such file or directory
[Error] Execution failed with error code: 1
```

**Comment by irinaespejo** [comment] 2019-09-09 16:23
Hi @khurtado, sad to hear that. I can't reproduce your error, could you post the commands you're using please? Also, you were using REANA + HTCondor + Singularity, does that still apply? Thanks!

**Comment by khurtado** [comment] 2019-09-09 21:06
@irinaespejo I'm running it via VC3 with REANA + HTCondor + Singularity, but I get similar results executing yadage-run alone in the following way:

# as a user:
```
export PACKTIVITY_CONTAINER_RUNTIME=singularity
export SINGULARITY_CACHEDIR="/tmp/$(whoami)/singularity"
export LC_ALL=en_US.utf-8
export LANG=en_US.utf-8
mkdir demo; cd demo
git clone https://github.com/scailfin/workflow-madminer
cd workflow-madminer/example-full
yadage-run   workdir workflow.yml  -p inputfile='"inputs/input.yml"'  -p njobs="6"  -p ntrainsamples="2"  -d initdir=$PWD --visualize
```

Once the above fails, the file in `workdir/configurate/_packtivity/configurate.run.log` has the following:

 `2019-09-09 16:58:09,580 | pack.configurate.run |   INFO | starting file logging for topic: run
2019-09-09 16:58:16,705 | pack.configurate.run |   INFO | inputfile:   /home/khurtado/demos/workflow-madminer/example-full/inputs/input.yml
2019-09-09 16:58:16,710 | pack.configurate.run |   INFO | Traceback (most recent call last):
2019-09-09 16:58:16,710 | pack.configurate.run |   INFO | File "/madminer/code/configurate.py", line 93, in <module>
2019-09-09 16:58:16,711 | pack.configurate.run |   INFO | miner.save('/madminer/data/madminer_example.h5')
2019-09-09 16:58:16,711 | pack.configurate.run |   INFO | File "/usr/local/lib/python2.7/dist-packages/madminer/core.py", line 527, in save
2019-09-09 16:58:16,711 | pack.configurate.run |   INFO | create_missing_folders([os.path.dirname(filename)])
2019-09-09 16:58:16,711 | pack.configurate.run |   INFO | File "/usr/local/lib/python2.7/dist-packages/madminer/utils/various.py", line 55, in create_missing_folders
2019-09-09 16:58:16,712 | pack.configurate.run |   INFO | os.makedirs(folder)
2019-09-09 16:58:16,712 | pack.configurate.run |   INFO | File "/usr/lib/python2.7/os.py", line 157, in makedirs
2019-09-09 16:58:16,712 | pack.configurate.run |   INFO | mkdir(name, mode)
2019-09-09 16:58:16,712 | pack.configurate.run |   INFO | OSError: [Errno 30] Read-only file system: '/madminer/data'
2019-09-09 16:58:16,857 | pack.configurate.run |   INFO | cp: cannot stat '/madminer/data/*.h5': No such file or directory
```

**Comment by khurtado** [comment] 2019-09-18 12:58
Hi @irinaespejo, did you get a chance to look into this? Let me know if there is anything else you need to reproduce the problem.

**Comment by irinaespejo** [comment] 2019-09-19 15:08
Hi @khurtado, sorry I've been a bit busy. I was able to reproduce your error. I have an idea of what might work, I'll let you know how that turns out. Thank you!

**Comment by irinaespejo** [comment] 2019-09-23 18:45
Hi @khurtado, could you try again the commands you posted and see if you still have the error? Thanks!

**Comment by khurtado** [comment] 2019-09-24 18:29
Hi @irinaespejo . Still the same error. I made sure to clean the singularity cache. Has anything changed in the code, though? I haven't noticed any new commit in this repo since Sep 17/18. 

```
2019-09-24 14:12:29,065 | pack.configurate.run |   INFO | File "/usr/local/lib/python2.7/dist-packages/madminer/utils/various.py", line 55, in create_missing_folders
2019-09-24 14:12:29,065 | pack.configurate.run |   INFO | os.makedirs(folder)
2019-09-24 14:12:29,065 | pack.configurate.run |   INFO | File "/usr/lib/python2.7/os.py", line 157, in makedirs
2019-09-24 14:12:29,065 | pack.configurate.run |   INFO | mkdir(name, mode)
2019-09-24 14:12:29,066 | pack.configurate.run |   INFO | OSError: [Errno 30] Read-only file system: '/madminer/data'
2019-09-24 14:12:29,167 | pack.configurate.run |   INFO | cp: cannot stat '/madminer/data/*.h5': No such file or directory
```

**Comment by khurtado** [comment] 2019-10-02 13:44
Hi @irinaespejo . Have you had a chance to look into this? Let me know if there is anything I can help with.

**Comment by khurtado** [comment] 2019-10-11 17:27
@irinaespejo Just ping about this to keep the thread alive :)

**Comment by khurtado** [comment] 2019-10-30 12:15
Hi @irinaespejo 

I'm trying to execute interactively. I get things running up to the combine step, but then sampling gives me the error below. Have you seen this?
I had to revert to madminer to 0.5.0, because otherwise, delphes would complain about systematics.

```
python configurate_ml.py 1 $data_file $input_file
['sally', 'alices', 'alice']
Traceback (most recent call last):
  File "configurate_ml.py", line 68, in <module>
    recalculate_header=True
  File "/usr/local/lib/python2.7/dist-packages/madminer/sampling.py", line 2020, in combine_and_shuffle
    all_observations, all_weights, all_sampling_ids = shuffle(all_observations, all_weights, all_sampling_ids)
  File "/usr/local/lib/python2.7/dist-packages/madminer/utils/various.py", line 98, in shuffle
    [None if val is None else val.shape for val in arrays]
RuntimeError: Mismatching shapes when trying to simultaneously shuffle: [(5823, 2), (5823, 6), (982,)]```

**Comment by khurtado** [comment] 2019-11-04 18:04
@irinaespejo Just so you know, the following changes work for me with singularity. I still need to check with shifter.

https://github.com/khurtado/workflow-madminer/commit/c4b3ac66820a3fe676c2d479f958346897640c20

**Comment by Sinclert** [comment] 2020-10-05 13:56
Closing issue, after confirmation with @khurtado over Slack.

**Closed by Sinclert** 2020-10-05 13:56 UTC
